# Generated by Django 3.2.2 on 2021-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requête', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=3, null=True)),
                ('continent', models.CharField(max_length=15, null=True)),
                ('region', models.CharField(max_length=25, null=True)),
                ('country', models.CharField(max_length=35, null=True)),
                ('hdi', models.FloatField(null=True)),
                ('population', models.IntegerField(null=True)),
                ('area_sql_ml', models.IntegerField(null=True)),
                ('climate', models.IntegerField(null=True)),
                ('date_premiere_vaccination', models.DateTimeField(null=True)),
            ],
        ),
    ]
